generate debuginfo packages
Signed-off-by: runsisi <runsisi@hust.edu.cn>

diff --git a/kernel.spec.in b/kernel.spec.in
--- a/kernel.spec.in
+++ b/kernel.spec.in
@@ -20,6 +20,8 @@
 %define with_perf    %{?_without_perf:    0} %{?!_without_perf:    1}
 # tools
 %define with_tools   %{?_without_tools:   0} %{?!_without_tools:   1}
+# kernel-debuginfo
+%define with_debuginfo %{?_without_debuginfo: 0} %{?!_without_debuginfo: 1}
 
 # These architectures install vdso/ directories.
 %define vdso_arches i686 x86_64
@@ -142,6 +144,14 @@ BuildRequires: slang-devel, xz-devel, zlib-devel
 %if %{with_tools}
 BuildRequires: gettext, ncurses-devel, pciutils, pciutils-devel, zlib-devel
 %endif
+%if %{with_debuginfo}
+# Fancy new debuginfo generation introduced in Fedora 8/RHEL 6.
+# The -r flag to find-debuginfo.sh invokes eu-strip --reloc-debug-sections
+# which reduces the number of relocations in kernel module .ko.debug files and
+# was introduced with rpm 4.9 and elfutils 0.153.
+BuildRequires: rpm-build >= 4.9.0-1, elfutils >= 0.153-1
+%define debuginfo_args --strict-build-id -r
+%endif
 
 # Sources.
 Source0: https://www.kernel.org/pub/linux/kernel/v4.x/linux-%{LKAver}.tar.xz
@@ -152,6 +162,8 @@ Source0: https://www.kernel.org/pub/linux/kernel/v4.x/linux-%{LKAver}.tar.xz
 Source3: config-%{version}-x86_64
 Source4: cpupower.service
 Source5: cpupower.config
+
+Patch1000: kernel-debuginfo.patch
 
 # Do not package the source tarball.
 NoSource: 0
@@ -219,6 +231,20 @@ License: GPLv2
 This package provides the perf tool and the supporting documentation
 for performance monitoring of the Linux kernel.
 
+%package -n perf-debuginfo
+Summary: Debug information for package perf
+Group: Development/Debug
+Requires: %{name}-debuginfo-common-%{_target_cpu} = %{version}-%{release}
+AutoReqProv: no
+%description -n perf-debuginfo
+This package provides debug information for the perf package.
+
+# Note that this pattern only works right to match the .build-id
+# symlinks because of the trailing nonmatching alternation and
+# the leading .*, because of find-debuginfo.sh's buggy handling
+# of matching the pattern against the symlinks file.
+%{expand:%%global debuginfo_args %{?debuginfo_args} -p '.*%%{_bindir}/perf(\.debug)?|.*%%{_bindir}/trace(\.debug)?|.*%%{_libexecdir}/perf-core/.*|.*%%{_libdir}/traceevent/plugins/.*|XXX' -o perf-debuginfo.list}
+
 %package -n python-perf
 Summary: Python bindings for applications that will manipulate perf events.
 Group: Development/Libraries
@@ -227,6 +253,17 @@ This package provides a module that permits applications written in the
 Python programming language to use the interface to manipulate perf events.
 
 %{!?python_sitearch: %global python_sitearch %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib(1)")}
+
+%package -n python-perf-debuginfo
+Summary: Debug information for package perf python bindings
+Group: Development/Debug
+Requires: %{name}-debuginfo-common-%{_target_cpu} = %{version}-%{release}
+AutoReqProv: no
+%description -n python-perf-debuginfo
+This package provides debug information for the perf python bindings.
+
+# the python_sitearch macro should already be defined from above
+%{expand:%%global debuginfo_args %{?debuginfo_args} -p '.*%%{python_sitearch}/perf.so(\.debug)?|XXX' -o python-perf-debuginfo.list}
 %endif
 
 %if %{with_tools}
@@ -269,10 +306,59 @@ Conflicts: kernel-tools-libs-devel < %{version}-%{release}
 %description -n %{name}-tools-libs-devel
 This package contains the development files for the tools/ directory
 libraries, derived from the kernel source.
+
+%package -n kernel-tools-debuginfo
+Summary: Debug information for package kernel-tools
+Group: Development/Debug
+Requires: %{name}-debuginfo-common-%{_target_cpu} = %{version}-%{release}
+AutoReqProv: no
+%description -n kernel-tools-debuginfo
+This package provides debug information for package kernel-tools.
+
+# Note that this pattern only works right to match the .build-id
+# symlinks because of the trailing nonmatching alternation and
+# the leading .*, because of find-debuginfo.sh's buggy handling
+# of matching the pattern against the symlinks file.
+%{expand:%%global debuginfo_args %{?debuginfo_args} -p '.*%%{_bindir}/centrino-decode(\.debug)?|.*%%{_bindir}/powernow-k8-decode(\.debug)?|.*%%{_bindir}/cpupower(\.debug)?|.*%%{_libdir}/libcpupower.*|.*%%{_libdir}/libcpupower.*|.*%%{_bindir}/turbostat(\.debug)?|.*%%{_bindir}/x86_energy_perf_policy(\.debug)?|.*%%{_bindir}/tmon(\.debug)?|XXX' -o kernel-tools-debuginfo.list}
 %endif
 
 # Disable the building of the debug package(s).
-%define debug_package %{nil}
+# NOTE: will be defined below, so comment it out here
+#%%define debug_package %{nil}
+
+%if !%{with_debuginfo}
+%define _enable_debug_packages 0
+%endif
+%define debuginfodir /usr/lib/debug
+
+%package debuginfo-common-%{_target_cpu}
+Summary: Kernel source files used by %{name}-debuginfo packages
+Group: Development/Debug
+%description debuginfo-common-%{_target_cpu}
+This package is required by %{name}-debuginfo subpackages.
+It provides the kernel source files common to all builds.
+
+%define KVRA %{version}-%{release}.%{_target_cpu}
+
+#
+# This macro creates a kernel-debuginfo package.
+#   %%kernel_debuginfo_package
+#
+%define kernel_debuginfo_package() \
+%package debuginfo\
+Summary: Debug information for package %{name}\
+Group: Development/Debug\
+Requires: %{name}-debuginfo-common-%{_target_cpu} = %{version}-%{release}\
+Provides: %{name}-debuginfo-%{_target_cpu} = %{version}-%{release}\
+AutoReqProv: no\
+%description -n %{name}-debuginfo\
+This package provides debug information for package %{name}.\
+This is required to use SystemTap with %{name}-%{KVRA}.\
+%{expand:%%global debuginfo_args %{?debuginfo_args} -p '/.*/%%{KVRA}/.*|/.*%%{KVRA}(\.debug)?' -o debuginfo.list}\
+%{nil}
+
+# the auxiliary packages of the main kernel package.
+%kernel_debuginfo_package
 
 %prep
 %setup -q -n %{name}-%{version} -c
@@ -285,6 +371,10 @@ pushd linux-%{version}-%{release}.%{_target_cpu} > /dev/null
 #%{__cp} %{SOURCE2} .
 #####################
 %{__cp} %{SOURCE3} .
+
+%if %{with_debuginfo}
+%patch1000 -p1
+%endif
 
 # Run make listnewconfig over all the configuration files.
 %ifarch i686 || x86_64
@@ -306,6 +396,16 @@ done
 popd > /dev/null
 
 %build
+%if %{with_debuginfo}
+# This override tweaks the kernel makefiles so that we run debugedit on an
+# object before embedding it.  When we later run find-debuginfo.sh, it will
+# run debugedit again.  The edits it does change the build ID bits embedded
+# in the stripped object, but repeating debugedit is a no-op.  We do it
+# beforehand to get the proper final build ID bits into the embedded image.
+# This affects the vDSO images in vmlinux, and the vmlinux image in bzImage.
+export AFTER_LINK='sh -xc "/usr/lib/rpm/debugedit -b $$RPM_BUILD_DIR -d /usr/src/debug -i $@ > $@.id"'
+%endif
+
 BuildKernel() {
     Flavour=$1
 
@@ -327,6 +427,9 @@ BuildKernel() {
     %{__make} -s ARCH=%{buildarch} %{?_smp_mflags} modules
 
     # Install the results into the RPM_BUILD_ROOT directory.
+%if %{with_debuginfo}
+    %{__mkdir_p} $RPM_BUILD_ROOT%{debuginfodir}/boot
+%endif
     %{__mkdir_p} $RPM_BUILD_ROOT/boot
     %{__install} -m 644 .config $RPM_BUILD_ROOT/boot/config-%{KVRFA}
     %{__install} -m 644 System.map $RPM_BUILD_ROOT/boot/System.map-%{KVRFA}
@@ -434,6 +537,21 @@ hwcap 1 nosegneg"
     # Remove any 'left-over' .cmd files.
     /usr/bin/find $RPM_BUILD_ROOT/lib/modules/%{KVRFA}/build -type f -name '*.cmd' | xargs --no-run-if-empty %{__rm} -f
 
+%if %{with_debuginfo}
+    if test -s vmlinux.id; then
+      %{__cp} vmlinux.id $RPM_BUILD_ROOT/lib/modules/%{KVRFA}/build/vmlinux.id
+    else
+      echo >&2 "*** ERROR *** no vmlinux build ID! ***"
+      exit 1
+    fi
+
+    #
+    # save the vmlinux file for kernel debugging into the kernel-debuginfo rpm
+    #
+    %{__mkdir_p} $RPM_BUILD_ROOT%{debuginfodir}/lib/modules/%{KVRFA}
+    %{__cp} vmlinux $RPM_BUILD_ROOT%{debuginfodir}/lib/modules/%{KVRFA}
+%endif
+
     /usr/bin/find $RPM_BUILD_ROOT/lib/modules/%{KVRFA} -type f -name '*.ko' > modnames
 
     # Mark the modules executable, so that strip-to-file can strip them.
@@ -540,6 +658,32 @@ popd > /dev/null
 %endif
 
 popd > /dev/null
+
+# This macro is used by %%install, so we must redefine it before that.
+%define debug_package %{nil}
+
+%if %{with_debuginfo}
+%define __debug_install_post \
+  /usr/lib/rpm/find-debuginfo.sh %{debuginfo_args} %{_builddir}/%{?buildsubdir}\
+%{nil}
+
+%ifnarch noarch
+%global __debug_package 1
+%files -f debugfiles.list debuginfo-common-%{_target_cpu}
+%defattr(-,root,root)
+%endif
+%endif
+
+#
+# Disgusting hack alert! We need to ensure we sign modules *after* all
+# invocations of strip occur, which is in __debug_install_post if
+# find-debuginfo.sh runs, and __os_install_post if not.
+#
+%define __spec_install_post \
+  %{?__debug_package:%{__debug_install_post}}\
+  %{__arch_install_post}\
+  %{__os_install_post}\
+%{nil}
 
 %install
 pushd linux-%{version}-%{release}.%{_target_cpu} > /dev/null
@@ -702,6 +846,13 @@ fi
 %defattr(-,root,root)
 %dir /usr/src/kernels
 /usr/src/kernels/%{version}-%{release}.%{_target_cpu}
+
+%if %{with_debuginfo}
+%ifnarch noarch
+%files -f debuginfo.list debuginfo
+%defattr(-,root,root)
+%endif
+%endif
 %endif
 
 %if %{with_headers}
@@ -739,6 +890,14 @@ fi
 %files -n python-perf
 %defattr(-,root,root)
 %{python_sitearch}
+
+%if %{with_debuginfo}
+%files -f perf-debuginfo.list -n perf-debuginfo
+%defattr(-,root,root)
+
+%files -f python-perf-debuginfo.list -n python-perf-debuginfo
+%defattr(-,root,root)
+%endif
 %endif
 
 %if %{with_tools}
@@ -771,9 +930,17 @@ fi
 %{_includedir}/cpufreq.h
 %{_includedir}/cpuidle.h
 %endif
+
+%if %{with_debuginfo}
+%files -f kernel-tools-debuginfo.list -n kernel-tools-debuginfo
+%defattr(-,root,root)
+%endif
 %endif
 
 %changelog
+* Wed Apr 26 2017 runsisi <runsisi@hust.edu.cn> - 4.10.11-2
+- generate debuginfo packages
+
 * Tue Apr 18 2017 Alan Bartlett <ajb@elrepo.org> - 4.10.11-1
 - Updated with the 4.10.11 source tarball.
 - [https://www.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.10.11]
